### ISSUE TITLE
ex2: Makefile

### ISSUE THREAD

**Issue by w1malik** [zedshaw/learn-c-the-hard-way-lectures#15]
The make command is quite confusing me while i carefully read your book and search some online website to deal with such error. I am running gedit on Linux machine in VMWare Workstation with terminal for make command running.
I tried to run ex1.c like this way:
make ex1 
It runs successfully. But the problem to not understanding even I have watched your video lectures. I did not quite understand as it is so confusing and you run so fast to cover that issue. 
The issue is where to place that Makefile. Actually problem to not pick up you are using vim editor. Where this Makefile should we place like. If I have the path of ex1 of lcthw\ex01\ex1.c then should i place makefile in this folder or the current folder in which i am going to place all exercise folder like lcthw\makefile thats it. and second thing is:
what is the extension of Makefile (.txt) or nothing to place anything after Makefile.
When i tried to run
make clean
I see this error message. How to clean this message.
make: *** No rule to make target `clean'.  Stop.
 I tried to check about the 4 spaces before (pne tab which is I set it 4 spaces in preferences in gedit)
1 CFLAGS=-Wall -g
2
3 clean:
4        rm -f ex1

Same question is asked over stackexchange twice. But still I am seeing ambiguity 
 http://stackoverflow.com/q/31704764   
http://stackoverflow.com/q/22255085
Suggestion for correction in pdf book:
The snapshot of Exercise 2 session which is as under:
$ make clean
rm -f ex1
$ make ex1
cc -Wall -g ex1.c -o ex1
ex1.c: In function 'main':
ex1.c:3: warning: implicit declaration of function 'puts'
Error "puts" needs to be replaced with printf function If see the error again please.

**Comment by mode-js** [comment]
Not sure if you have received an answer on this - but pretty sure the Makefile needs to be in the directory of where you are compiling the code from.  the book is pretty clear on where to save it and how to name it etc.... here is a snippet that should answer most of your questions.  

(there is no extension to the Makefile -- it is just called Makefile and when you run the "make" command it will pull the dependencies and arguments that you've placed within the Makefile).
<img width="805" alt="screen shot 2017-07-15 at 10 23 15 pm" src="https://user-images.githubusercontent.com/29901608/28244884-89433acc-69ac-11e7-93db-623b5368f776.png">

**Comment by gbonnema** [comment]
> I tried to check about the 4 spaces before (pne tab which is I set it 4 spaces in preferences in gedit)
> 1 CFLAGS=-Wall -g
> 2
> 3 clean:
> 4 rm -f ex1
> 

The Makefile is pretty sensitive to tabs. You have to start line 4 with a tab or it will not recognize clean.

**Comment by zedshaw** [comment]
Don't forget we also have a form at https://forum.learncodethehardway.com/
